spring:
  data:
    mongodb:
      uri: mongodb+srv://shubhamdongare9696:Shubham%40007@cluster0.xearc.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
  main:
    allow-bean-definition-overriding: true

elevenlabs:
  api:
    base-url: https://api.elevenlabs.io/v1
    key: sk_bb91dc6db9bee055e0d4ee1c5a5de51d6ddada36bc3c70bc

webflux:
    max-in-memory-size: 10MB

#mvc:
#  static-path-pattern: /static/**
server:
  port: 8080 # Optional: Define the server port


