spring:
  data:
    mongodb:
      uri: mongodb+srv://shubhamdongare9696:Shubham%40007@cluster0.xearc.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb

elevenlabs:
  api:
    base-url: https://api.elevenlabs.io/v1
    key: sk_bb91dc6db9bee055e0d4ee1c5a5de51d6ddada36bc3c70bc

webflux:
  max-in-memory-size: 32MB

weather:
  api:
    key: babea779fae4b4fd9793e4e377b82cb8
    base-url: https://api.weatherstack.com
server:
  port: 8080
