spring:
  data:
    mongodb:
      uri: mongodb+srv://shubhamdongare9696:Shubham%40007@cluster0.xearc.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
  main:
    allow-bean-definition-overriding: true
#mvc:
#  static-path-pattern: /static/**
server:
  port: 8080 # Optional: Define the server port


